### ISSUE TITLE
Feature: Add CATs logs as an output

### ISSUE THREAD

**Issue by aashah** [cloudfoundry/cats-concourse-task#4]
The CAPI team uploads our CATs logs to external storage for further debugging red builds. It would be cool if this task supported that.

Thanks

**Comment by dsabeti** [comment]
Hey @aashah. I'm thinking of a pretty simple implementation for this. We could update the interface to this:
```
...
inputs:
- name: cats-concourse-task
- name: cf-acceptance-tests
- name: integration-config

outputs:
- name: logs

params:
  NODES: 12
  CONFIG_FILE_PATH: integration_config.json
  CAPTURE_LOGS: false
```

If `CAPTURE_LOGS` is set to true, the task throws the logs in the `logs` output. A downstream Concourse step (most likely a `put`) can manage uploading the the logs to the desired bucket. Would that help for you?
